In [ ]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("zomato.csv")

In [ ]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1.0,0.0,NaN,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2.0,0.0,NaN,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2.0,0.0,NaN,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3.0,0.0,NaN,NaN,0.0,2.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4.0,0.0,NaN,NaN,0.0,3.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [36]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 7105
Columns: 12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB

In [37]:
df.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [38]:
df["restaurant type"] = df["restaurant type"].fillna("Unknown")
df["cuisines type"] = df["cuisines type"].fillna("Unknown")
df["local address"] = df["local address"].fillna("Unknown")

In [40]:
df["rate (out of 5)"] = df["rate (out of 5)"].fillna(df["rate (out of 5)"].mean())

In [41]:
df = df.drop_duplicates()

print("Remaining rows:", len(df))

Remaining rows: 7105

In [43]:
text_columns = [
    "restaurant name",
    "restaurant type",
    "cuisines type",
    "area",
    "local address"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.title()

df["online_order"] = df["online_order"].astype(str).str.strip().str.lower()
df["table booking"] = df["table booking"].astype(str).str.strip().str.lower()

In [44]:
df["rate (out of 5)"] = pd.to_numeric(df["rate (out of 5)"], errors="coerce")

df["num of ratings"] = pd.to_numeric(df["num of ratings"], errors="coerce")

df["avg cost (two people)"] = pd.to_numeric(df["avg cost (two people)"], errors="coerce")

In [46]:
df.rename(columns={
    "restaurant name":"restaurant_name",
    "restaurant type":"restaurant_type",
    "rate (out of 5)":"rating",
    "num of ratings":"num_ratings",
    "avg cost (two people)":"avg_cost_two_people",
    "table booking":"table_booking",
    "online_order":"online_order",
    "cuisines type":"cuisines_type",
    "local address":"local_address"
}, inplace=True)

In [48]:
df["rating_category"] = np.where(
    df["rating"] >= 4,
    "Highly Rated",
    "Average Rated"
)

In [49]:
df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant_name,restaurant_type,rating,num_ratings,avg_cost_two_people,online_order,table_booking,cuisines_type,area,local_address,rating_category
0,0,0,#Feeltheroll,Quick Bites,3.4,7,200.0,no,no,Fast Food,Bellandur,Bellandur,Average Rated
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,yes,no,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",Hsr,Average Rated
2,2,2,#Refuel,Cafe,3.7,37,400.0,yes,no,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road,Average Rated
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,yes,no,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli,Average Rated
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,yes,no,"Bbq, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur,Average Rated

In [51]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [52]:
from google.colab import files

files.download("cleaned_dataset.csv")